### ISSUE TITLE
Make qt-pods compatible.

### ISSUE THREAD

**Issue by cybercatalyst** [qterminal/qtermwidget#41]
I am currently accumulating projects for qt-pods, an easy x-platform way to install Qt libs in project scope without cluttering the system environment. For a basic understanding see here:
https://github.com/cybercatalyst/qt-pods

It would be cool got get qtermwidget compatible, so I can list it as a pos and make it available for developers. If you have questions or need assistance, don't hesitate to ask.

J

**Comment by pvanek** [comment]
hi Jacob,

there are some things I don't understant in qt-pods. You say it's based on git submodules in qmake's subdirs project template.

But how I can include a cmake based library in it?

And before you start "convert to qmake" rant listen to these reasons ;)

- qmake sucks ;)
- currently the CMakeLists.txt contains some checks for defines, and functions. To do it in qmake is a pain in the ass. So it's not just "list all files in .pro file"

So is it possible to make a qt-pod with cmake?

**Comment by cybercatalyst** [comment]
I know this debate is emotionally loaded. As the maintainer of qt-pods I am trying to be neutral on this.

So generally, my opinion is: Yes, I want to have cmake embedded, if people wish to use this. But this is a dilemma here: If I say let's switch to cmake, people will complain that I don't use the standard build system for Qt. If I say let's switch to qmake, people with cmake projects will be excluded. I just want to make clear that this is a difficult situation for all of us. qt-pods wants to unify things (because unified is less error-prone and better to use).

So here are three completely objective reasons for qmake (undeniable):
* qmake is the standard.
* qmake i s supported out-of-the-box, ie you do not have to install cmake next to the Qt developer tools.
* Writing checks is difficult, but it is possible (no K.O. criteria).

As a maintainer I have the responsibility to weigh the advantages and disadvantages. "qmake sucks" is not a differentiated opinion I guess. By switching to cmake I am doing the project more bad than good.

**Comment by pvanek** [comment]
I know, it was somehow a joke. A bit. And I really don't take qmake as a 2nd level citizen. I just don't like to use it.

My original note was not about in what is the qtpod is using qmake etc. But mostly about that there are some SW using different build systems like cmake. In this case you cannot expect that maintainer of the SW will change the build system for this.

So the question is about: how to include cmake based library in qtpod. Is it possible?

**Comment by cybercatalyst** [comment]
I think it could be done with qmakes "system"-command I think: http://stackoverflow.com/questions/20886813/cmake-project-inside-a-qmake-project

There is already an open issue on that:
https://github.com/cybercatalyst/qt-pods/issues/4

"All" qt-pods expects is the following:
A folder with a *.pro that builds a static lib.
A *.pri that specifies include paths and the libs the target links against.

**Comment by cybercatalyst** [comment]
Ok, I have forked the project and made the transition to qmake. I gave you proper credit in the README. It's the second time I work on this codebase btw :P In 2012 I stripped half of it for Octave.

**Comment by pvanek** [comment]
cool. I hope it can results in some upstream contributions ;)

BTW I plan to create something like "libvte" for Qt. The plan is to pickup konsole core, make it standalone library with Qt5 deps only (as KFramework5 probably) and replace qtermwidget with it. One day. It would join all contributors into one project. Konsole terminal will remain KDE project though.

**Comment by cybercatalyst** [comment]
There will never be such a thing like an official Qt terminal widget I fear. That's because you would need a platform-independent way of creating a terminal. This is difficult especially on Windows, where you do not have the concept of ptys.

What you can do on Windows is mirror an existing console into another window, which is a hacky but working way. But then you have no control about anything.

What I have done with QTermWidget: I stripped the whole session management and the shell connection. Then I connected the process where the widget was running in with the the widget. That's because Octave was usually running on a pty and we just wanted to connect the pty in GUI-ish way to preserve all the neat terminal functionality.

I am not sure if you can benefit from my code, but I can open a pull request. That solely depends if you want to stick to cmake at any cost or we can get it running with qmake, so we could develop on the same codebase.
