### ISSUE TITLE
Port qtermwidget to Windows 

### ISSUE THREAD

**Issue by x-a-n-a-x** [qterminal/qtermwidget#42]
Hello.

How hard would it be to port qtermwidget to Windows?

Reference issue: https://github.com/Swordfish90/cool-retro-term/issues/40#issuecomment-73375027

Thanks.

**Comment by jleclanche** [comment]
PRs accepted, but we're not leaving a tracker bug open for this.

**Comment by Climax777** [comment]
which elements are specifically not for Windows? I need a terminal emulation widget which doesn't specifically call a shell program. I have remote serial comms which I want terminal emulation for, and it has to support Windows. I am willing to do the port as far as is possible for cross platform in Windows.

**Comment by tpham3783** [comment]
I tried today, but ran into problems w/ linux's ioctrl calls.

**Comment by yan12125** [comment]
For anyone coming to this issue: Octave forked qtermwidget and added win32 support [1][2]. It might be a good start point.

[1] https://hg.savannah.gnu.org/hgweb/octave/file/af7faef288ad/libgui/qterminal/libqterminal/
[2] https://github.com/lxqt/qtermwidget/issues/240
