### ISSUE TITLE
[!] CMake Error at CMakeLists.txt:169 (message). Please have a look.

### ISSUE THREAD

**Issue by MuSamDu** [qterminal/qtermwidget#47]
I'm trying to compile the sources following your instructions, and I'm running KDE Plasma5, which uses Qt5. After i type "cmake .. -DUSE_QT5=true" in my build directory, it shows these and stopped.

>-- The C compiler identification is GNU 4.9.3
>-- The CXX compiler identification is GNU 4.9.3
>-- Check for working C compiler: /usr/bin/cc
>-- Check for working C compiler: /usr/bin/cc -- works
>-- Detecting C compiler ABI info
>-- Detecting C compiler ABI info - done
>-- Detecting C compile features
>-- Detecting C compile features - done
>-- Check for working CXX compiler: /usr/bin/c++
>-- Check for working CXX compiler: /usr/bin/c++ -- works
>-- Detecting CXX compiler ABI info
>-- Detecting CXX compiler ABI info - done
>-- Detecting CXX compile features
>-- Detecting CXX compile features - done
>-- Keyboard layouts will be installed in: /usr/local/share/qtermwidget5/kb-layouts
>-- Color schemes will be installed in: /usr/local/share/qtermwidget5/color-schemes
>-- Looking for updwtmpx
>-- Looking for updwtmpx - found
>>-- qtermwidget5: writing pkgconfig file /home/msd/Downloads/qtermwidget/build/qtermwidget5.pc
>>CMake Error at CMakeLists.txt:169 (message):
>> Building Qt designer plugin is not supported for Qt5 yet.  Use
>>  -DBUILD_DESIGNER_PLUGIN=0
>>
>>
>>-- Configuring incomplete, errors occurred!
>>See also "/home/msd/Downloads/qtermwidget/build/CMakeFiles/CMakeOutput.log".

Please tell me what the hell is going on and have a try to solve it, Thanks a lot!

**Comment by worblehat** [comment]
As the error message says: When compiling with Qt5 you have to add "-DBUILD_DESIGNER_PLUGIN=0" to your CMake command.
